SERVICE_PROVIDERS = [
    {
        "id": 1,
        "name": "Ali Hassan",
        "service_type": "AC Technician",
        "area": "G-13",
        "lat": 33.6493,
        "long": 72.9692,
        "distance_from_g13_km": 0.0,
        "rating": 4.8,
        "available_slots": ["9:00 AM", "11:00 AM", "2:00 PM"],
        "phone": "0300-1234567",
        "price_per_hour": 1500,
       "experience_years": 7,
"bio": "Certified AC technician specializing in split and inverter units. Served 200+ clients across Islamabad.",
"jobs_completed": 214,
 },

    {
        "id": 2,
        "name": "Fatima Ahmed",
        "service_type": "Beautician",
        "area": "F-7",
        "lat": 33.7200,
        "long": 73.0500,
        "distance_from_g13_km": 11.5,
        "rating": 4.9,
        "available_slots": ["10:00 AM", "1:00 PM", "4:00 PM"],
        "phone": "0311-2345678",
        "price_per_hour": 2500,
        "experience_years": 6,
"bio": "Professional beautician trained in Karachi. Specializes in bridal makeup, threading, and skincare.",
"jobs_completed": 340,
    },

    {
        "id": 3,
        "name": "Ahmed Raza",
        "service_type": "Plumber",
        "area": "I-8",
        "lat": 33.6680,
        "long": 73.0750,
        "distance_from_g13_km": 9.8,
        "rating": 4.5,
        "available_slots": ["9:00 AM", "12:00 PM", "3:00 PM"],
        "phone": "0322-3456789",
        "price_per_hour": 1200,
        "experience_years": 5,
"bio": "Affordable and reliable plumbing services. Available for emergency calls with same-day response.",
"jobs_completed": 189,
    },

    {
        "id": 4,
        "name": "Zainab Fatima",
        "service_type": "Tutor",
        "area": "G-11",
        "lat": 33.6670,
        "long": 72.9970,
        "distance_from_g13_km": 3.2,
        "rating": 4.7,
        "available_slots": ["3:00 PM", "5:00 PM", "7:00 PM"],
        "phone": "0333-4567890",
        "price_per_hour": 2000,
        "experience_years": 5,
"bio": "O/A Level tutor for Mathematics and Sciences. 95% of students showed grade improvement.",
"jobs_completed": 180,
    },

    {
        "id": 5,
        "name": "Umer Ahmed",
        "service_type": "Electrician",
        "area": "F-6",
        "lat": 33.7290,
        "long": 73.0740,
        "distance_from_g13_km": 13.5,
        "rating": 4.6,
        "available_slots": ["11:00 AM", "2:00 PM", "5:00 PM"],
        "phone": "0344-5678901",
        "price_per_hour": 1800,
        "experience_years": 8,
"bio": "Licensed electrician for wiring, load balancing, DB installation, and inverter/UPS setup.",
"jobs_completed": 356,
    },

    {
        "id": 6,
        "name": "Bilal Hassan",
        "service_type": "Carpenter",
        "area": "E-7",
        "lat": 33.7310,
        "long": 73.0410,
        "distance_from_g13_km": 12.0,
        "rating": 4.4,
        "available_slots": ["9:00 AM", "1:00 PM"],
        "phone": "0300-6789012",
        "price_per_hour": 1600,
        "experience_years": 11,
"bio": "Master carpenter for custom furniture, door frames, kitchen cabinets, and wood polishing.",
"jobs_completed": 498,
    },

    {
        "id": 7,
        "name": "Sajid Khan",
        "service_type": "AC Technician",
        "area": "H-13",
        "lat": 33.6350,
        "long": 72.9550,
        "distance_from_g13_km": 2.5,
        "rating": 4.2,
        "available_slots": ["10:00 AM", "12:00 PM", "4:00 PM"],
        "phone": "0321-7890123",
        "price_per_hour": 1400,
        "experience_years": 4,
"bio": "Experienced in all major AC brands including Gree, Haier, and Dawlance. Quick diagnosis and repair.",
"jobs_completed": 128,
    },

    {
        "id": 8,
        "name": "Ayesha Ahmed",
        "service_type": "Beautician",
        "area": "G-9",
        "lat": 33.6840,
        "long": 73.0300,
        "distance_from_g13_km": 7.0,
        "rating": 4.8,
        "available_slots": ["11:00 AM", "3:00 PM", "6:00 PM"],
        "phone": "0312-8901234",
        "price_per_hour": 2200,
        "experience_years": 5,
"bio": "Home-based beauty service provider. Expert in mehndi, facials, and hair styling for all occasions.",
"jobs_completed": 275,
    },

    {
        "id": 9,
        "name": "Tariq Ali",
        "service_type": "Plumber",
        "area": "F-10",
        "lat": 33.7000,
        "long": 73.0000,
        "distance_from_g13_km": 6.5,
        "rating": 4.3,
        "available_slots": ["9:00 AM", "11:00 AM", "2:00 PM"],
        "phone": "0334-9012345",
        "price_per_hour": 1300,
        "experience_years": 9,
"bio": "Master plumber handling leakages, pipe fitting, bathroom installation, and water pump repair.",
"jobs_completed": 412,
    },

    {
        "id": 10,
        "name": "Marium Fatima",
        "service_type": "Tutor",
        "area": "F-11",
        "lat": 33.6900,
        "long": 72.9800,
        "distance_from_g13_km": 4.8,
        "rating": 4.9,
        "available_slots": ["4:00 PM", "6:00 PM", "8:00 PM"],
        "phone": "0345-0123456",
        "price_per_hour": 2100,
        "experience_years": 7,
"bio": "Experienced home tutor for primary to intermediate level. Specializes in English and Urdu literature.",
"jobs_completed": 240,
    },

    {
        "id": 11,
        "name": "Kamran Hassan",
        "service_type": "Electrician",
        "area": "G-8",
        "lat": 33.6950,
        "long": 73.0450,
        "distance_from_g13_km": 10.2,
        "rating": 4.5,
        "available_slots": ["10:00 AM", "1:00 PM", "3:00 PM"],
        "phone": "0300-1112233",
        "price_per_hour": 1700,
        "experience_years": 6,
"bio": "Specialist in home wiring, MCB replacement, and solar panel connections. Safety-first approach.",
"jobs_completed": 223,
    },

    {
        "id": 12,
        "name": "Irfan Raza",
        "service_type": "Carpenter",
        "area": "I-9",
        "lat": 33.6550,
        "long": 73.0600,
        "distance_from_g13_km": 8.5,
        "rating": 4.1,
        "available_slots": ["12:00 PM", "4:00 PM"],
        "phone": "0321-2223344",
        "price_per_hour": 1500,
        "experience_years": 6,
"bio": "Affordable carpentry for home repairs, wardrobes, and wooden flooring installation.",
"jobs_completed": 167,
    },
]
